// Generated by CoffeeScript 1.6.3
module.exports = function(root, toUrl) {
  var fs, path, url;
  if (toUrl == null) {
    toUrl = '/';
  }
  fs = require('fs');
  path = require('path');
  url = require('url');
  return function(req, res, next) {
    var absolutePath;
    absolutePath = path.join(root, url.parse(req.url).pathname);
    return fs.exists(absolutePath, function(exists) {
      if (!exists) {
        req.url = toUrl;
      }
      return next();
    });
  };
};
